import requests
import datetime
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os
import sys

# Europe PMC API endpoint
EPMC_API_URL = "https://www.ebi.ac.uk/europepmc/webservices/rest/search"

# Categories and their specific queries
CATEGORIES = {
    "Glutathione": '("Saccharomyces cerevisiae" OR "baker\'s yeast") AND "glutathione"',
    "NMN": '("Saccharomyces cerevisiae" OR "baker\'s yeast") AND ("NMN" OR "Nicotinamide mononucleotide")',
    "Gene Editing Tools": '("Saccharomyces cerevisiae" OR "baker\'s yeast") AND ("gene editing" OR "CRISPR" OR "TALEN" OR "ZFN" OR "Cas9")'
}

def fetch_recent_papers(query, days=2):
    """
    Fetch papers from Europe PMC for a given query over the past `days` days.
    Europe PMC includes PubMed, PMC, bioRxiv, medRxiv, etc.
    """
    today = datetime.datetime.now()
    past_date = today - datetime.timedelta(days=days)
    
    date_str = f"[{past_date.strftime('%Y-%m-%d')} TO {today.strftime('%Y-%m-%d')}]"
    full_query = f"{query} AND (FIRST_PDATE:{date_str})"
    
    params = {
        "query": full_query,
        "format": "json",
        "resultType": "core", # core includes abstract
        "pageSize": 20
    }
    
    try:
        response = requests.get(EPMC_API_URL, params=params)
        response.raise_for_status()
        data = response.json()
        return data.get("resultList", {}).get("result", [])
    except Exception as e:
        print(f"Error fetching data for query '{query}': {e}")
        return []

def format_html_email(results_by_category):
    """
    Format the results into a clean HTML email.
    """
    html = """
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
            h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
            h2 { color: #2980b9; margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
            .paper { background: #f9f9f9; padding: 15px; border-radius: 5px; margin-bottom: 20px; border-left: 4px solid #3498db; }
            .title { font-size: 18px; font-weight: bold; margin-bottom: 5px; color: #2c3e50; }
            .authors { font-size: 14px; color: #7f8c8d; margin-bottom: 10px; font-style: italic; }
            .journal { font-size: 14px; font-weight: bold; color: #e67e22; }
            .abstract { font-size: 14px; margin-bottom: 15px; text-align: justify; }
            .link-btn { display: inline-block; background: #3498db; color: #fff; text-decoration: none; padding: 8px 15px; border-radius: 3px; font-size: 14px; }
            .link-btn:hover { background: #2980b9; }
            .no-papers { color: #7f8c8d; font-style: italic; }
        </style>
    </head>
    <body>
        <h1>🧬 S. cerevisiae Daily Literature Update</h1>
        <p>Here are the latest papers and preprints regarding S. cerevisiae, categorized by your topics of interest. Collected over the last 48 hours.</p>
    """
    
    total_papers = 0
    for category, papers in results_by_category.items():
        html += f"<h2>📌 {category}</h2>"
        if not papers:
            html += "<p class='no-papers'>No new papers found for this category today.</p>"
            continue
            
        for paper in papers:
            total_papers += 1
            title = paper.get('title', 'No Title Available')
            authors = paper.get('authorString', 'Authors not listed')
            journal = paper.get('journalTitle', paper.get('bookOrReportDetails', {}).get('publisher', 'Preprint/Unknown Source'))
            abstract = paper.get('abstractText', 'No abstract available.')
            doi = paper.get('doi')
            pmid = paper.get('pmid')
            
            link = f"https://doi.org/{doi}" if doi else (f"https://pubmed.ncbi.nlm.nih.gov/{pmid}" if pmid else "#")
            
            # Truncate abstract if it's too long
            if len(abstract) > 800:
                abstract = abstract[:800] + "... (truncated)"
                
            html += f"""
            <div class="paper">
                <div class="title">{title}</div>
                <div class="authors">{authors}</div>
                <div class="journal">Source: {journal}</div>
                <div class="abstract"><strong>Abstract:</strong><br>{abstract}</div>
                <a href="{link}" class="link-btn" target="_blank">Read Full Paper</a>
            </div>
            """
            
    html += """
        <br><hr>
        <p style="font-size: 12px; color: #95a5a6; text-align: center;">Automatically generated by S. cerevisiae Literature Updater using Europe PMC API.</p>
    </body>
    </html>
    """
    return html, total_papers

def send_email(html_content, total_papers):
    sender_email = os.environ.get("EMAIL_SENDER")
    sender_password = os.environ.get("EMAIL_PASSWORD")
    receiver_email = os.environ.get("EMAIL_RECEIVER")
    
    if not all([sender_email, sender_password, receiver_email]):
        print("Email credentials are not set in environment variables.")
        return
        
    msg = MIMEMultipart("alternative")
    today_str = datetime.datetime.now().strftime('%Y-%m-%d')
    msg["Subject"] = f"[{today_str}] S. cerevisiae Literature Update ({total_papers} new)"
    msg["From"] = sender_email
    msg["To"] = receiver_email
    
    part = MIMEText(html_content, "html")
    msg.attach(part)
    
    try:
        # Using Naver SMTP
        server = smtplib.SMTP_SSL("smtp.naver.com", 465)
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print("Email sent successfully!")
    except Exception as e:
        print(f"Failed to send email: {e}")

def main():
    print("Starting S. cerevisiae literature update process...")
    results_by_category = {}
    
    for category, query in CATEGORIES.items():
        print(f"Fetching data for: {category}")
        papers = fetch_recent_papers(query)
        results_by_category[category] = papers
        print(f"Found {len(papers)} papers for {category}.")
        
    html_content, total_papers = format_html_email(results_by_category)
    
    if total_papers > 0:
        send_email(html_content, total_papers)
    else:
        print("No new papers found across all categories. Not sending email to avoid spam.")

if __name__ == "__main__":
    main()
